"""add photo_url to users table

Revision ID: cb6fa63211b3
Revises: 6c4c83e58268
Create Date: 2026-01-04 19:19:09.166840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb6fa63211b3'
down_revision: Union[str, None] = '6c4c83e58268'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('google_calendar_event_id', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('reminder_sent_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('photo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'photo_url')
    op.drop_column('appointments', 'reminder_sent_at')
    op.drop_column('appointments', 'google_calendar_event_id')
    # ### end Alembic commands ###
